
/*
TODO:


Warum funktioniert Ganztonlieiter nicht? Nur 6 Töne funktioniert nicht! Der Cluster mit 6 Ganztönen ist auch Hindemith-Kategorie 11!
Eigentlich will ich bei Root doch \frei einstellen können. Als Folge sollte ich daneben einen Parameter haben in dem man Root-Skala eingibt (weil natürlich verschiedene Akkordgrundtöne in einer Skala vorkommen).
Knopf: Such nen anderen Akkord mit den gleichen Parametern. (~trees-Dictionary?)
Spreading-Parameter? Knopf, der "Zusammenfegt"?
*/