Beim ersten Fraktal eine Variation rein bringen.
Insgesamt Exposition:

DissGrade RootNote NumNotes
9, 0, 6
List: [ 3, 6, 7, 8, 16, 24 ]


Entwicklung 1
DissGrade RootNote NumNotes
4, 0, 6
List: [ 2, 4, 7, 10, 12, 19 ]

Enwicklung 2 (Synth: Penrose Enwicklung 2)
Spielen:
6, 0, 6
6, 0, 7
7, 0 ,6
7, 0, 7 => List: [ 2, 3, 7, 11, 12, 16, 19 ]

Stutter
4, 0, 3
[ 4, 6, 12 ]

axiom: F7G7-F+F2- F+F+F+F+F+F 4- F+F+F+F+F+F2-FFFF
rule:




FRAKTAL-FUGE
Puls ist Achtel.
Axiomteil_1:
Takte_1bis4: 2g2a5+6a-a+a-a-a-a-a+2a2-2a+2a+2a+2a+2a2-a+a-2a2-
Takte_5bis8: a+a+a+a+a+a+a+a3-4a-2a+2a2a3-2a2a2a2+
Takte_9bis12: 2a-2a+2a3-2a3+2a-2a-2a3+4a2-2a3-2a+4a-a2+3a-2a

Axiomteil_2:
Takte_1bis4: 4+2g2a5+6a-a+a-a-a-a-a+2a2-2a+2a+2a+2a+2a2-a+a-2a3- //wie Axiomteil_1 Takte 1 bis 4
Takte_5bis8: a+a+a+a+a+a+a+a3-4a-2a+2a2a3-2a2a2a3+ //wie Axiomteil_1 Takte 5 bis 8
Takte_9bis12: 2a-2a+2a3-2a3+2a-2a-2a3+4a2-2a3-2a+4a-a2+3a-2a //wie Axoimteil_1 Takte 9 bis 12

Axiom, Takte 1 bis 24:
2g2a5+6a-a+a-a-a-a-a+2a2-2a+2a+2a+2a+2a2-a+a-2a
[4+2g2a5+6a-a+a-a-a-a-a+2a2-2a+2a+2a+2a+2a2-a+a-2a3-a+a+a+a+a+a+a+a3-4a-2a+2a2a3-2a2a2a3+2a-2a+2a3-2a3+2a-2a-2a3+4a2-2a3-2a+4a-a2+3a-2a/*T5-16*/
2g2a5+6a-a+a-a-a-a-a+2a2-2a+2a+2a+2a+2a2-a+a-2a2-a+a+a+a+a+a+a+a3-4a-2a+2a2a3-2a2a2a2+2a-2a+2a3-2a3+2a-2a-2a3+4a2-2a3-2a+4a-a2+3a-2a]/*T17-20*/
2-a+a+a+a+a+a+a+a3-4a-2a+2a2a3-2a2a2a
[8-2g2a5+6a-a+a-a-a-a-a+2a2-2a+2a+2a+2a+2a2-a+a-2a2-a+a+a+a+a+a+a+a3-4a-2a+2a2a3-2a2a2a2+2a-2a+2a3-2a3+2a-2a-2a3+4a2-2a3-2a+4a-a2+3a-2a
	4+2g2a5+6a-a+a-a-a-a-a+2a2-2a+2a+2a+2a+2a2-a+a-2a3-a+a+a+a+a+a+a+a3-4a-2a+2a2a3-2a2a2a3+2a-2a+2a3-2a3+2a-2a-2a3+4a2-2a3-2a+4a-a2+3a-2a]
2+2a-2a+2a3-2a3+2a-2a-2a3+4a2-2a3-2a+4a-a2+3a-2a
3-2g2a5+6a-a+a-a-a-a-a+2a2-2a+2a+2a+2a+2a2-a+a-2a3-a+a+a+a+a+a+a+a3-4a-2a+2a2a3-2a2a2a3+2a-2a+2a3-2a3+2a-2a-2a3+4a2-2a3-2a+4a-a2+3a-2a






